### ISSUE TITLE
About the license

### ISSUE THREAD

**Issue by deunlee** [janbodnar/Java-Sokoban-Game#3]
Hi, there

I would like to use this code as a simple example program in a university course. However, there seems to be no license in this repository. So I'd like you to add licenses to this.

Tip: Click `Add File` in this repository, then enter the file name as `LICENSE` and you will see a license selection button at the top right.

Thanks.

**Comment by janbodnar** [comment]
Hi, I have added the license.

**Comment by deunlee** [comment]
Thanks!
